# config.yml
backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "establishments"
    label: "Establishments"
    folder: "content/establishments"
    create: true
    fields:
      - { label: "Establishment Name", name: "name", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Kosher Status", name: "kosher_status", widget: "string" }
      - { label: "Certificate", name: "certificate", widget: "image" }
    access:
      roles: ["admin", "mashgiach"]

  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    fields:
      - { label: "Product Name", name: "name", widget: "string" }
      - { label: "Kosher Status", name: "kosher_status", widget: "string" }
      - { label: "Product Brand", name: "brand", widget: "string" }
    access:
      roles: ["admin", "mashgiach"]

  - name: "mashgiach_logs"
    label: "Mashgiach Logs"
    folder: "content/logs"
    create: true
    fields:
      - { label: "Establishment", name: "establishment", widget: "relation", collection: "establishments", searchFields: ["name"], valueField: "name" }
      - { label: "Mashgiach Name", name: "mashgiach_name", widget: "string" }
      - { label: "Time and Date", name: "time_date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
    access:
      roles: ["admin", "mashgiach"]

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
    access:
      roles: ["admin"]
