[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  # Explicitly disabling Go
  GO_IMPORT_PATH = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
